# Generated by Django 3.2.16 on 2022-11-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('recipient_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recepient',
                'verbose_name_plural': 'Recepients',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transfer_code', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.UUIDField(blank=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('source', models.CharField(blank=True, default='balance', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recepient', to='payment.recepient')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transfer_code', models.CharField(blank=True, max_length=50)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=15)),
                ('source', models.CharField(blank=True, max_length=15)),
                ('reference', models.UUIDField(blank=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recepient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_recepient', to='payment.recepient')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_transfer', to='payment.transfer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
