# Generated by Django 3.2.16 on 2022-11-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepient',
            new_name='Recipient',
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('-created_at',), 'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recepient',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='recepient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_recipient', to='payment.recipient'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipient', to='payment.recipient'),
            preserve_default=False,
        ),
    ]
