# Generated by Django 3.2.16 on 2022-11-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20221105_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='type',
            field=models.CharField(blank=True, default='mobile_money', max_length=50, null=True),
        ),
    ]
