# Generated by Django 3.2.16 on 2022-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
