# Generated by Django 3.2.16 on 2022-11-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_transaction_fee_charged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
