# Generated by Django 3.2.16 on 2022-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('longcode', models.CharField(blank=True, max_length=50)),
                ('gateway', models.CharField(max_length=50, null=True)),
                ('pay_with_bank', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bank',
                'ordering': ('-created_at',),
            },
        ),
    ]
