# Generated by Django 3.2.16 on 2022-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('-created_at',), 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
